[package]
name = "kata"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-junit = "0.8.0"
parameterized = "1.0.1"
