name: Rust

on:
  push:
    branches: [ "rust/number-in-words/*" ]
  pull_request:
    branches: [ "rust/number-in-words/*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo
          ./target/debug/deps
        key: cargo-cache-{{ checksum "Cargo.toml" }}
    - name: Run tests
      run: cargo test
