name: Rust

on:
  push:
    branches: [ "rust/numbers-in-words" ]
  pull_request:
    branches: [ "rust/numbers-in-words" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --verbose
